import data from "@/lib/threat-actors.json";

export interface ThreatActor {
  id: string;
  name: string;
  aliases: string[];
  description: string;
  url: string;
  techniqueCount: number;
  software: string[];
  modified: string;
}

// Generated by `npm run refresh-threat-actors` from the MITRE ATT&CK bundle.
export const threatActors = data.actors as ThreatActor[];
export const threatActorsUpdated = data.updated;
